ci: prpl-jira.py: fix unicode decode errors
Explicitly ignore unicode decoding errors when processing job artifacts,
by setting `open()`'s optional argument `errors` to `ignore`. Default
value is set to `strict` which in some corner cases, like for example in
the serial console log might produce following exception:

  Traceback (most recent call last):
    File ".gitlab/scripts/prpl-jira.py", line 454, in <module>
      main()
    File ".gitlab/scripts/prpl-jira.py", line 450, in main
      args.func(prpl_jira)
    File ".gitlab/scripts/prpl-jira.py", line 348, in run_failure
      issue = self.create_or_update_issue("run", log_analyzer.failures_jira_string())
    File ".gitlab/scripts/prpl-jira.py", line 136, in failures_jira_string
      console_log = self.logfile_tail_content("console")
    File ".gitlab/scripts/prpl-jira.py", line 122, in logfile_tail_content
      data.extend(f.readlines())
    File "/usr/lib/python3.7/codecs.py", line 322, in decode
      (result, consumed) = self._buffer_decode(data, self.errors, final)
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 3414: invalid continuation byte

References: https://gitlab.com/prpl-foundation/prplwrt/prplwrt/-/jobs/1246737319#L112
Signed-off-by: Petr Štetiar <ynezz@true.cz>