ci: testbed-device.py: fix rax40 wait for network timeout issue
Since commit 96e413e6ccea ("ci: labgrid: rax40: ensure clean system state") we
always boot into the clean system (first boot state) and it seems like the
network stack needs more time then current 30 seconds to become operational:

 $ .gitlab/scripts/testbed-device.py --target $LABGRID_TARGET check_network --network lan --remote-host $TARGET_LAN_TEST_HOST
 Traceback (most recent call last):
   File ".gitlab/scripts/testbed-device.py", line 130, in <module>
     main()
   File ".gitlab/scripts/testbed-device.py", line 126, in main
     args.func(device)
   File ".gitlab/scripts/testbed-device.py", line 42, in check_network
     'ifstatus {} | jsonfilter -qe "@.up" || true'.format(network), "true"
   File "/usr/local/lib/python3.7/dist-packages/labgrid-0.2.1.dev514+g81d1b16-py3.7.egg/labgrid/driver/commandmixin.py", line 34, in wait_for
     raise ExecutionError("Wait timeout expired")
  labgrid.driver.exception.ExecutionError: Wait timeout expired

So fix this by increasing the timeout to 60 seconds.

Signed-off-by: Petr Štetiar <ynezz@true.cz>