ci: builder: add missing python-yaml dependency for prplMesh
Fixes following issue which will arise once we start building prplmesh:

 Traceback (most recent call last):
   File "prplmesh-1.4.0-eb2327daaff7c4e5071dcfb9ddd75c88f2b747a7/framework/tlvf/tlvf.py", line 20, in <module>
     import yaml
 ImportError: No module named yaml

Signed-off-by: Petr Štetiar <ynezz@true.cz>