ci: fix jira Python module missing pyjwt dependency
Seems like there is some missing package dependency on pyjwt somewhere
in jira Python package dependency chain which results in following issue
during automatic Jira issue creation:

 Traceback (most recent call last):
  File ".gitlab/scripts/prpl-jira.py", line 454, in <module>
    main()
  ...
  File "/usr/local/lib/python3.7/dist-packages/jira/client.py", line 506, in __init__
    si = self.server_info()
  ...
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  ...
  File "/usr/local/lib/python3.7/dist-packages/requests_oauthlib/oauth1_auth.py", line 109, in __call__
    unicode(r.url), unicode(r.method), None, r.headers
  ...
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth1/rfc5849/__init__.py", line 313, in sign
    ('oauth_signature', self.get_oauth_signature(request)))
  ...
  File "/usr/local/lib/python3.7/dist-packages/oauthlib/oauth1/rfc5849/signature.py", line 560, in _jwt_rs1_signing_algorithm
    import jwt.algorithms as jwtalgo
 ModuleNotFoundError: No module named 'jwt'

Fix it by explicitly installing pyjwt Python module and improve test
coverage so it doesn't regress again in the future.

References: https://gitlab.com/prpl-foundation/prplwrt/prplwrt/-/jobs/1277104142
Signed-off-by: Petr Štetiar <ynezz@true.cz>