ci: prpl-jira.py: handle missing log files
Fixes following exception caused by missing log files from Cram tests
which happened as the RAX40 device didn't booted properly before the
testing:

 Traceback (most recent call last):
   File ".gitlab/scripts/prpl-jira.py", line 450, in <module>
     main()
   File ".gitlab/scripts/prpl-jira.py", line 446, in main
     args.func(prpl_jira)
   File ".gitlab/scripts/prpl-jira.py", line 344, in run_failure
     issue = self.create_or_update_issue("run", log_analyzer.failures_jira_string())
   File ".gitlab/scripts/prpl-jira.py", line 131, in failures_jira_string
     cram_log = self.logfile_content("cram")
   File ".gitlab/scripts/prpl-jira.py", line 88, in logfile_content
     path = self.logfile_path(kind)
   File ".gitlab/scripts/prpl-jira.py", line 96, in logfile_path
     return os.path.join(self._log_dir, self._log_files.get(kind))
   File "/usr/lib/python3.7/posixpath.py", line 94, in join
     genericpath._check_arg_types('join', a, *p)
   File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
     (funcname, s.__class__.__name__)) from None
 TypeError: join() argument must be str or bytes, not 'NoneType'

Fixes: f309b1ad19bf ("ci: prpl-jira.py: add support for handling of run failures")
Signed-off-by: Petr Štetiar <ynezz@true.cz>