ci: build: workaround dictionary keys changed during iteration error
Seems like Python 3.8 introduced change, which is causing issues in
python-jira library when adding attachments:

 File "scripts/gitlab/prpl-jira.py", line 136, in build_failure
     self.jira.add_attachment(
   File "/usr/local/lib/python3.8/site-packages/jira/client.py", line 126, in wrapper
     result = func(*arg_list, **kwargs)
   File "/usr/local/lib/python3.8/site-packages/jira/client.py", line 787, in add_attachment
     url, data=m, headers=CaseInsensitiveDict({'content-type': m.content_type, 'X-Atlassian-Token': 'nocheck'}), retry_data=file_stream)
   File "/usr/local/lib/python3.8/site-packages/jira/utils/__init__.py", line 41, in __init__
     for key, value in super(CaseInsensitiveDict, self).items():
 RuntimeError: dictionary keys changed during iteration

Until it's fixed upstream, workaround it by using Python 3.7, otherwise
we would need to maintain our own fork of jira-python library.

Ref: https://bugs.python.org/issue36452
Ref: https://github.com/pycontribs/jira/issues/890
Signed-off-by: Petr Štetiar <ynezz@true.cz>